### ISSUE TITLE
Enable offline testing with video recordings

### ISSUE THREAD

**Issue by AG6GR** [Tino-FRC-2473/FRC2019-Vision#5]
We need to be able to test our algorithms on our own computers, without the Jetson. This requires that we be able to record camera footage easily and run the CV code on pre-recorded video.

See commit a219a4c78053772ba7067127b2803eafc9d06d49 for hints.

**Comment by michelllepan** [comment]
Today I got code working for running from video input using the command line arguments, and I'm close to finishing video output as well, but I ran into some issues with the type of the image width and height. I also made it an option to pass in the camera port number as an argument so that can solve our problems with opening up the files to change the number.

By Thursday I'll hopefully get the video output working so we can test that on the Jetson, and also integrate subprocess.
